name: Django CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # mesma versão da EC2

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Testar aplicação
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py test

      - name: Deploy para EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.EC2_USER }}
            git -C CashPilot fetch origin main
            git -C CashPilot checkout main
            git -C CashPilot reset --hard origin/main

            # cria venv se não existir
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi

            # ativa venv e instala dependências
            source venv/bin/activate
            pip install -r CashPilot/requirements.txt  # <-- corrigido aqui

            # entra no projeto e roda comandos Django
            cd CashPilot
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput

            # reinicia os serviços
            sudo systemctl restart gunicorn.service
            sudo systemctl restart nginx.service

            echo "✅ Deploy finalizado com sucesso em $(date)"

